version: '3'
services:
    php74-ap74:
      build:
        context: ./images/php74
        args:
          - USER_ID
          - GROUP_ID
      external_links:
        - mysql:mysql
      volumes:
        - ./www:/var/www
      environment:
        - XDEBUG_CONFIG=remote_host=192.168.220.1 remote_enable=1 remote_autostart=off  remote_port=9008
        - PHP_IDE_CONFIG=serverName=magento.loc
        - PMA_HOST=mysql
        - PMA_PORT=3306
    nginx-serve:
      image: nginx
      volumes:
        - ./hosts:/etc/nginx/conf.d
        - ./www:/var/www
        - ./logs:/var/log/nginx
      ports:
        - "80:80"
      depends_on:
        - php74-ap74
        - mysql
        - phpmyadmin
    mysql:
      image: mysql:5.7
      ports:
        - "3306:3306"
      volumes:
        - ./mysql/data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: secret
    phpmyadmin:
      container_name: phpmyadmin
      hostname: phpmyadmin
      domainname: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - '2200:80'
      environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
      external_links:
        - mysql:mysql
      volumes:
        - ./phpmyadmin/sessions:/sessions
networks:
  default:
    ipam:
      driver: default
      config:
         - subnet: 172.30.0.0/16