version: '3.3'
services:
  es5.6:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: es5.6
    hostname: es5.6
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
