version: '3.3'
services:
  es7.9:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es7.9
    hostname: es7.9
    environment:
      - node.name=es7.9
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
